routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TermodinamicaController;
use App\Http\Controllers\SoundController;
use App\Http\Controllers\EnergyController;
use App\Http\Controllers\ForceController;
use App\Http\Controllers\PendularController;
use App\Http\Controllers\ParabolController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
Route::get('/termodinamica', [TermodinamicaController::class, 'index'])->name('termodinamica');
Route::get('/fuerza', [ForceController::class, 'index'])->name('fuerza');
Route::get('/energia', [EnergyController::class, 'index'])->name('energia');
Route::get('/pendulo', [PendularController::class, 'index'])->name('pendulo');
Route::get('/parabolico', [ParabolController::class, 'index'])->name('parabolico');
Route::get('sonido', [SoundController::class, 'index'])->name('sonido');

app/Http/Livewire/Parabol.php
<?php

namespace App\Http\Livewire;
use Illuminate\Support\Facades\Http;

use Livewire\Component;

class Parabol extends Component
{
    public $velinicial=1,  $aceleracion = 1 , $tiempo =1, $grado =0;
    public  $tiempo_caidalibre=1, $velocidad_inicial=1 , $posicion_inicial=1;
    
    public function render()
    {
        $respuesta = HTTP::get('https://api-grupo6.herokuapp.com/movimiento_parabolico?velinicial='.$this->velinicial.'&aceleracion='.$this->aceleracion.'&tiempo='.$this->tiempo);
        $res = $respuesta -> json();    
    
        $respuestas = HTTP::get('https://api-grupo6.herokuapp.com/caida_libre?posicion_inicial='.$this->posicion_inicial.'&velocidad_inicial='.$this->velocidad_inicial.'&tiempo_caidalibre='.$this->tiempo_caidalibre);
        $res2 = $respuestas -> json();

        return view('livewire.pendular', compact('res', 'res2'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/energia.blade.php
<x-app-layout>

                <livewire:energy/>
    
</x-app-layout>

resources/views/pages/fuerza.blade.php
<x-app-layout>

                <livewire:force/>
    
</x-app-layout>

resources/views/pages/parabolico.blade.php
<x-app-layout>

                <livewire:parabol/>
    
</x-app-layout>

resources/views/pages/pendulo.blade.php
<x-app-layout>

                <livewire:pendular/>
    
</x-app-layout>

resources/views/pages/sonido.blade.php
<x-app-layout>

                <livewire:sound/>
    
</x-app-layout>

resources/views/pages/termodinamica.blade.php
<x-app-layout>
                <livewire:termodinamica />
</x-app-layout>